// India States, Cities and representative Pincodes data

export interface CityData {
    name: string;
    pincode: string;
}

export interface StateData {
    name: string;
    cities: CityData[];
}

export const INDIA_DATA: StateData[] = [
    {
        name: "Andhra Pradesh",
        cities: [
            { name: "Visakhapatnam", pincode: "530001" },
            { name: "Vijayawada", pincode: "520001" },
            { name: "Guntur", pincode: "522001" },
            { name: "Nellore", pincode: "524001" },
            { name: "Kurnool", pincode: "518001" },
            { name: "Rajahmundry", pincode: "533101" },
            { name: "Tirupati", pincode: "517501" },
            { name: "Kakinada", pincode: "533001" },
            { name: "Anantapur", pincode: "515001" },
            { name: "Kadapa", pincode: "516001" },
            { name: "Eluru", pincode: "534001" },
            { name: "Ongole", pincode: "523001" },
            { name: "Chittoor", pincode: "517001" },
            { name: "Proddatur", pincode: "516360" },
            { name: "Bhimavaram", pincode: "534201" },
        ],
    },
    {
        name: "Arunachal Pradesh",
        cities: [
            { name: "Itanagar", pincode: "791111" },
            { name: "Naharlagun", pincode: "791110" },
            { name: "Pasighat", pincode: "791102" },
            { name: "Tezpur", pincode: "784001" },
            { name: "Bomdila", pincode: "790001" },
        ],
    },
    {
        name: "Assam",
        cities: [
            { name: "Guwahati", pincode: "781001" },
            { name: "Silchar", pincode: "788001" },
            { name: "Dibrugarh", pincode: "786001" },
            { name: "Jorhat", pincode: "785001" },
            { name: "Nagaon", pincode: "782001" },
            { name: "Tinsukia", pincode: "786125" },
            { name: "Bongaigaon", pincode: "783380" },
            { name: "Goalpara", pincode: "783101" },
            { name: "Dhubri", pincode: "783301" },
        ],
    },
    {
        name: "Bihar",
        cities: [
            { name: "Patna", pincode: "800001" },
            { name: "Gaya", pincode: "823001" },
            { name: "Bhagalpur", pincode: "812001" },
            { name: "Muzaffarpur", pincode: "842001" },
            { name: "Darbhanga", pincode: "846001" },
            { name: "Purnia", pincode: "854301" },
            { name: "Arrah", pincode: "802301" },
            { name: "Begusarai", pincode: "851101" },
            { name: "Katihar", pincode: "854105" },
            { name: "Munger", pincode: "811201" },
            { name: "Chhapra", pincode: "841301" },
            { name: "Samastipur", pincode: "848101" },
        ],
    },
    {
        name: "Chhattisgarh",
        cities: [
            { name: "Raipur", pincode: "492001" },
            { name: "Bhilai", pincode: "490001" },
            { name: "Bilaspur", pincode: "495001" },
            { name: "Korba", pincode: "495677" },
            { name: "Durg", pincode: "491001" },
            { name: "Raigarh", pincode: "496001" },
            { name: "Jagdalpur", pincode: "494001" },
            { name: "Rajnandgaon", pincode: "491441" },
        ],
    },
    {
        name: "Goa",
        cities: [
            { name: "Panaji", pincode: "403001" },
            { name: "Margao", pincode: "403601" },
            { name: "Vasco da Gama", pincode: "403802" },
            { name: "Mapusa", pincode: "403507" },
            { name: "Ponda", pincode: "403401" },
        ],
    },
    {
        name: "Gujarat",
        cities: [
            { name: "Ahmedabad", pincode: "380001" },
            { name: "Surat", pincode: "395001" },
            { name: "Vadodara", pincode: "390001" },
            { name: "Rajkot", pincode: "360001" },
            { name: "Bhavnagar", pincode: "364001" },
            { name: "Jamnagar", pincode: "361001" },
            { name: "Junagadh", pincode: "362001" },
            { name: "Gandhinagar", pincode: "382001" },
            { name: "Anand", pincode: "388001" },
            { name: "Navsari", pincode: "396445" },
            { name: "Morbi", pincode: "363641" },
            { name: "Mehsana", pincode: "384001" },
            { name: "Bharuch", pincode: "392001" },
            { name: "Vapi", pincode: "396191" },
            { name: "Gandhidham", pincode: "370201" },
        ],
    },
    {
        name: "Haryana",
        cities: [
            { name: "Faridabad", pincode: "121001" },
            { name: "Gurugram", pincode: "122001" },
            { name: "Panipat", pincode: "132001" },
            { name: "Ambala", pincode: "134003" },
            { name: "Yamunanagar", pincode: "135001" },
            { name: "Rohtak", pincode: "124001" },
            { name: "Hisar", pincode: "125001" },
            { name: "Karnal", pincode: "132001" },
            { name: "Sonipat", pincode: "131001" },
            { name: "Panchkula", pincode: "134109" },
            { name: "Bhiwani", pincode: "127021" },
            { name: "Sirsa", pincode: "125055" },
            { name: "Bahadurgarh", pincode: "124507" },
        ],
    },
    {
        name: "Himachal Pradesh",
        cities: [
            { name: "Shimla", pincode: "171001" },
            { name: "Solan", pincode: "173212" },
            { name: "Dharamsala", pincode: "176215" },
            { name: "Mandi", pincode: "175001" },
            { name: "Kullu", pincode: "175101" },
            { name: "Kangra", pincode: "176001" },
            { name: "Baddi", pincode: "173205" },
        ],
    },
    {
        name: "Jharkhand",
        cities: [
            { name: "Ranchi", pincode: "834001" },
            { name: "Jamshedpur", pincode: "831001" },
            { name: "Dhanbad", pincode: "826001" },
            { name: "Bokaro", pincode: "827001" },
            { name: "Deoghar", pincode: "814112" },
            { name: "Phusro", pincode: "829144" },
            { name: "Hazaribag", pincode: "825301" },
            { name: "Giridih", pincode: "815301" },
            { name: "Dumka", pincode: "814101" },
        ],
    },
    {
        name: "Karnataka",
        cities: [
            { name: "Bengaluru", pincode: "560001" },
            { name: "Mysuru", pincode: "570001" },
            { name: "Mangaluru", pincode: "575001" },
            { name: "Hubballi", pincode: "580020" },
            { name: "Dharwad", pincode: "580001" },
            { name: "Belagavi", pincode: "590001" },
            { name: "Davanagere", pincode: "577001" },
            { name: "Ballari", pincode: "583101" },
            { name: "Vijayapura", pincode: "586101" },
            { name: "Shivamogga", pincode: "577201" },
            { name: "Tumakuru", pincode: "572101" },
            { name: "Raichur", pincode: "584101" },
            { name: "Kalaburagi", pincode: "585101" },
            { name: "Bidar", pincode: "585401" },
            { name: "Udupi", pincode: "576101" },
            { name: "Kolar", pincode: "563101" },
            { name: "Mandya", pincode: "571401" },
            { name: "Hassan", pincode: "573201" },
            { name: "Chikkamagaluru", pincode: "577101" },
        ],
    },
    {
        name: "Kerala",
        cities: [
            { name: "Thiruvananthapuram", pincode: "695001" },
            { name: "Kochi", pincode: "682001" },
            { name: "Kozhikode", pincode: "673001" },
            { name: "Kannur", pincode: "670001" },
            { name: "Thrissur", pincode: "680001" },
            { name: "Kollam", pincode: "691001" },
            { name: "Palakkad", pincode: "678001" },
            { name: "Alappuzha", pincode: "688001" },
            { name: "Malappuram", pincode: "676501" },
            { name: "Kottayam", pincode: "686001" },
            { name: "Ernakulam", pincode: "682011" },
            { name: "Pathanamthitta", pincode: "689645" },
        ],
    },
    {
        name: "Madhya Pradesh",
        cities: [
            { name: "Indore", pincode: "452001" },
            { name: "Bhopal", pincode: "462001" },
            { name: "Jabalpur", pincode: "482001" },
            { name: "Gwalior", pincode: "474001" },
            { name: "Ujjain", pincode: "456001" },
            { name: "Sagar", pincode: "470001" },
            { name: "Dewas", pincode: "455001" },
            { name: "Satna", pincode: "485001" },
            { name: "Ratlam", pincode: "457001" },
            { name: "Rewa", pincode: "486001" },
            { name: "Murwara", pincode: "483501" },
            { name: "Singrauli", pincode: "486889" },
            { name: "Burhanpur", pincode: "450331" },
            { name: "Khargone", pincode: "451001" },
            { name: "Chhindwara", pincode: "480001" },
        ],
    },
    {
        name: "Maharashtra",
        cities: [
            { name: "Mumbai", pincode: "400001" },
            { name: "Pune", pincode: "411001" },
            { name: "Nagpur", pincode: "440001" },
            { name: "Nashik", pincode: "422001" },
            { name: "Aurangabad", pincode: "431001" },
            { name: "Solapur", pincode: "413001" },
            { name: "Amravati", pincode: "444601" },
            { name: "Kolhapur", pincode: "416001" },
            { name: "Navi Mumbai", pincode: "400703" },
            { name: "Thane", pincode: "400601" },
            { name: "Kalyan", pincode: "421301" },
            { name: "Vasai-Virar", pincode: "401201" },
            { name: "Latur", pincode: "413512" },
            { name: "Dhule", pincode: "424001" },
            { name: "Ahmednagar", pincode: "414001" },
            { name: "Akola", pincode: "444001" },
            { name: "Jalgaon", pincode: "425001" },
            { name: "Sangli", pincode: "416416" },
            { name: "Satara", pincode: "415001" },
            { name: "Ratnagiri", pincode: "415612" },
        ],
    },
    {
        name: "Manipur",
        cities: [
            { name: "Imphal", pincode: "795001" },
            { name: "Thoubal", pincode: "795138" },
            { name: "Bishnupur", pincode: "795126" },
        ],
    },
    {
        name: "Meghalaya",
        cities: [
            { name: "Shillong", pincode: "793001" },
            { name: "Tura", pincode: "794001" },
            { name: "Nongstoin", pincode: "793119" },
        ],
    },
    {
        name: "Mizoram",
        cities: [
            { name: "Aizawl", pincode: "796001" },
            { name: "Lunglei", pincode: "796701" },
            { name: "Champhai", pincode: "796321" },
        ],
    },
    {
        name: "Nagaland",
        cities: [
            { name: "Kohima", pincode: "797001" },
            { name: "Dimapur", pincode: "797112" },
            { name: "Mokokchung", pincode: "798601" },
        ],
    },
    {
        name: "Odisha",
        cities: [
            { name: "Bhubaneswar", pincode: "751001" },
            { name: "Cuttack", pincode: "753001" },
            { name: "Rourkela", pincode: "769001" },
            { name: "Brahmapur", pincode: "760001" },
            { name: "Sambalpur", pincode: "768001" },
            { name: "Puri", pincode: "752001" },
            { name: "Balasore", pincode: "756001" },
            { name: "Bhadrak", pincode: "756100" },
            { name: "Baripada", pincode: "757001" },
            { name: "Jharsuguda", pincode: "768201" },
        ],
    },
    {
        name: "Punjab",
        cities: [
            { name: "Ludhiana", pincode: "141001" },
            { name: "Amritsar", pincode: "143001" },
            { name: "Jalandhar", pincode: "144001" },
            { name: "Patiala", pincode: "147001" },
            { name: "Bathinda", pincode: "151001" },
            { name: "Mohali", pincode: "160055" },
            { name: "Hoshiarpur", pincode: "146001" },
            { name: "Gurdaspur", pincode: "143521" },
            { name: "Pathankot", pincode: "145001" },
            { name: "Moga", pincode: "142001" },
        ],
    },
    {
        name: "Rajasthan",
        cities: [
            { name: "Jaipur", pincode: "302001" },
            { name: "Jodhpur", pincode: "342001" },
            { name: "Udaipur", pincode: "313001" },
            { name: "Kota", pincode: "324001" },
            { name: "Ajmer", pincode: "305001" },
            { name: "Bikaner", pincode: "334001" },
            { name: "Alwar", pincode: "301001" },
            { name: "Bharatpur", pincode: "321001" },
            { name: "Sikar", pincode: "332001" },
            { name: "Sri Ganganagar", pincode: "335001" },
            { name: "Pali", pincode: "306401" },
            { name: "Bhilwara", pincode: "311001" },
            { name: "Barmer", pincode: "344001" },
            { name: "Jaisalmer", pincode: "345001" },
        ],
    },
    {
        name: "Sikkim",
        cities: [
            { name: "Gangtok", pincode: "737101" },
            { name: "Namchi", pincode: "737126" },
            { name: "Mangan", pincode: "737116" },
        ],
    },
    {
        name: "Tamil Nadu",
        cities: [
            { name: "Chennai", pincode: "600001" },
            { name: "Coimbatore", pincode: "641001" },
            { name: "Madurai", pincode: "625001" },
            { name: "Tiruchirappalli", pincode: "620001" },
            { name: "Salem", pincode: "636001" },
            { name: "Tirunelveli", pincode: "627001" },
            { name: "Erode", pincode: "638001" },
            { name: "Vellore", pincode: "632001" },
            { name: "Thoothukudi", pincode: "628001" },
            { name: "Dindigul", pincode: "624001" },
            { name: "Tiruppur", pincode: "641601" },
            { name: "Thanjavur", pincode: "613001" },
            { name: "Ranipet", pincode: "632401" },
            { name: "Cuddalore", pincode: "607001" },
            { name: "Kanchipuram", pincode: "631501" },
            { name: "Nagercoil", pincode: "629001" },
            { name: "Kumbakonam", pincode: "612001" },
            { name: "Hosur", pincode: "635109" },
        ],
    },
    {
        name: "Telangana",
        cities: [
            { name: "Hyderabad", pincode: "500001" },
            { name: "Warangal", pincode: "506001" },
            { name: "Nizamabad", pincode: "503001" },
            { name: "Khammam", pincode: "507001" },
            { name: "Karimnagar", pincode: "505001" },
            { name: "Ramagundam", pincode: "505208" },
            { name: "Mahbubnagar", pincode: "509001" },
            { name: "Nalgonda", pincode: "508001" },
            { name: "Adilabad", pincode: "504001" },
            { name: "Suryapet", pincode: "508213" },
            { name: "Siddipet", pincode: "502103" },
        ],
    },
    {
        name: "Tripura",
        cities: [
            { name: "Agartala", pincode: "799001" },
            { name: "Dharmanagar", pincode: "799250" },
            { name: "Udaipur", pincode: "799120" },
        ],
    },
    {
        name: "Uttar Pradesh",
        cities: [
            { name: "Lucknow", pincode: "226001" },
            { name: "Kanpur", pincode: "208001" },
            { name: "Agra", pincode: "282001" },
            { name: "Varanasi", pincode: "221001" },
            { name: "Prayagraj", pincode: "211001" },
            { name: "Ghaziabad", pincode: "201001" },
            { name: "Meerut", pincode: "250001" },
            { name: "Noida", pincode: "201301" },
            { name: "Mathura", pincode: "281001" },
            { name: "Aligarh", pincode: "202001" },
            { name: "Bareilly", pincode: "243001" },
            { name: "Moradabad", pincode: "244001" },
            { name: "Gorakhpur", pincode: "273001" },
            { name: "Muzaffarnagar", pincode: "251001" },
            { name: "Saharanpur", pincode: "247001" },
            { name: "Jhansi", pincode: "284001" },
            { name: "Firozabad", pincode: "283203" },
            { name: "Lakhimpur", pincode: "262701" },
            { name: "Hapur", pincode: "245101" },
            { name: "Unnao", pincode: "209801" },
        ],
    },
    {
        name: "Uttarakhand",
        cities: [
            { name: "Dehradun", pincode: "248001" },
            { name: "Haridwar", pincode: "249401" },
            { name: "Roorkee", pincode: "247667" },
            { name: "Haldwani", pincode: "263139" },
            { name: "Nainital", pincode: "263001" },
            { name: "Kashipur", pincode: "244713" },
            { name: "Rishikesh", pincode: "249201" },
            { name: "Rudrapur", pincode: "263153" },
        ],
    },
    {
        name: "West Bengal",
        cities: [
            { name: "Kolkata", pincode: "700001" },
            { name: "Asansol", pincode: "713301" },
            { name: "Siliguri", pincode: "734001" },
            { name: "Durgapur", pincode: "713201" },
            { name: "Bardhaman", pincode: "713101" },
            { name: "Malda", pincode: "732101" },
            { name: "Baharampur", pincode: "742101" },
            { name: "Habra", pincode: "743268" },
            { name: "Kharagpur", pincode: "721301" },
            { name: "Shantipur", pincode: "741402" },
            { name: "Darjeeling", pincode: "734101" },
            { name: "Haldia", pincode: "721602" },
        ],
    },
    // Union Territories
    {
        name: "Andaman and Nicobar Islands",
        cities: [
            { name: "Port Blair", pincode: "744101" },
            { name: "Car Nicobar", pincode: "744301" },
        ],
    },
    {
        name: "Chandigarh",
        cities: [
            { name: "Chandigarh", pincode: "160001" },
            { name: "Manimajra", pincode: "160101" },
            { name: "Panchkula", pincode: "134112" },
        ],
    },
    {
        name: "Dadra and Nagar Haveli and Daman and Diu",
        cities: [
            { name: "Daman", pincode: "396210" },
            { name: "Silvassa", pincode: "396230" },
            { name: "Diu", pincode: "362520" },
        ],
    },
    {
        name: "Delhi",
        cities: [
            { name: "New Delhi", pincode: "110001" },
            { name: "Old Delhi", pincode: "110006" },
            { name: "Noida (Delhi NCR)", pincode: "110096" },
            { name: "Dwarka", pincode: "110075" },
            { name: "Saket", pincode: "110017" },
            { name: "Rohini", pincode: "110085" },
            { name: "Lajpat Nagar", pincode: "110024" },
            { name: "Pitampura", pincode: "110034" },
            { name: "Janakpuri", pincode: "110058" },
            { name: "Karol Bagh", pincode: "110005" },
        ],
    },
    {
        name: "Jammu and Kashmir",
        cities: [
            { name: "Srinagar", pincode: "190001" },
            { name: "Jammu", pincode: "180001" },
            { name: "Anantnag", pincode: "192101" },
            { name: "Baramulla", pincode: "193101" },
            { name: "Sopore", pincode: "193201" },
        ],
    },
    {
        name: "Ladakh",
        cities: [
            { name: "Leh", pincode: "194101" },
            { name: "Kargil", pincode: "194103" },
        ],
    },
    {
        name: "Lakshadweep",
        cities: [
            { name: "Kavaratti", pincode: "682555" },
            { name: "Agatti", pincode: "682553" },
        ],
    },
    {
        name: "Puducherry",
        cities: [
            { name: "Puducherry", pincode: "605001" },
            { name: "Karaikal", pincode: "609601" },
            { name: "Mahe", pincode: "673310" },
            { name: "Yanam", pincode: "533464" },
        ],
    },
];

export const STATES = INDIA_DATA.map((s) => s.name);

export const getCitiesForState = (stateName: string): CityData[] => {
    const state = INDIA_DATA.find((s) => s.name === stateName);
    return state ? state.cities : [];
};

export const getPincodeForCity = (stateName: string, cityName: string): string => {
    const state = INDIA_DATA.find((s) => s.name === stateName);
    if (!state) return "";
    const city = state.cities.find((c) => c.name === cityName);
    return city ? city.pincode : "";
};
